x-postgres-env: &postgres-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres

services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      <<: *postgres-env
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  import:
    build:
      context: ./import
    command: ./import.sh
    environment:
      <<: *postgres-env
    volumes:
      - ./import/data:/workdir/data
    depends_on:
      postgres:
        condition: service_started
  api:
    build:
      context: ./api
    environment:
      <<: *postgres-env
    ports:
      - 80:80
    depends_on:
      import:
        condition: service_completed_successfully

volumes:
  postgres:
